-- Schema PostgreSQL/Supabase da Calçados Mariano.
--
-- Este arquivo define a estrutura do catálogo. A conexão com o banco fica em
-- src/config/db.js; a aplicação não cria nem migra tabelas ao iniciar.
--
-- categoria = tipo do calçado.
-- publico   = público do calçado.
-- numeracao é TEXT porque existem valores como '35/36'.

CREATE TABLE IF NOT EXISTS produtos (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome           TEXT,
    numeracao      TEXT,
    categoria      TEXT,
    publico        TEXT,
    subcategoria   TEXT,
    quantidade     INTEGER,
    status_estoque TEXT,
    marca          TEXT,
    cor            TEXT,
    descricao      TEXT,
    imagem_url     TEXT,
    nome_ordenacao TEXT
);
